# Generated by Django 4.0.5 on 2022-11-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0011_alter_user_role'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_user.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lot',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
