# Generated by Django 4.0.5 on 2022-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
