# Generated by Django 4.1.2 on 2022-10-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_user', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_category', to='apps_user.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300)),
                ('price1', models.FloatField(blank=True, null=True)),
                ('price2', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(max_length=5000, null=True)),
                ('temporarily_unavailable', models.BooleanField(default=False)),
                ('pictures', models.FileField(blank=True, null=True, upload_to='product')),
                ('expiration_date', models.DateTimeField()),
                ('count', models.IntegerField(blank=True, null=True)),
                ('count_of_product', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
