# Generated by Django 4.0.5 on 2022-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temporarily',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
